language: node_js

os:
  - osx

node_js:
  - "10"

script:
  - npm run build:prod

cache:
  directories:
    - node_modules

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $PL_GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: dist
  on:
    branch: master